version = 1

[[annotations]]
path = ["metadata.json", "translate/template.pot", "translate/*.po"]
SPDX-FileCopyrightText = "2026 Mark Hellewell <aussieweather.sandlot200@passinbox.com>"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = ["README.md", "CHANGELOG.md", "docs/**"]
SPDX-FileCopyrightText = "2026 Mark Hellewell <aussieweather.sandlot200@passinbox.com>"
SPDX-License-Identifier = "GPL-2.0-or-later"
